### PR TITLE
Apply merged-/usr for post-bookworm+ (to include bookworm later)

### PR DESCRIPTION
**Pull request by tianon**
See https://lists.debian.org/debian-ctte/2022/07/msg00034.html

Refs https://github.com/debuerreotype/docker-debian-artifacts/issues/131 (not Closes until it includes bookworm :eyes:)

### CODE REVIEW

**Comment by tianon** [comment]
(The biggest benefit to this implementation is that it only changes `examples/` so I don't have to do a full release to iterate now or when it's time to include bookworm :eyes:)

**Comment by tianon** [comment]
Hmm, I guess it's not really appropriate to apply this to unstable builds from 2017 since that unstable won't support it properly.  This needs a timestamp filter too. :sweat_smile:

**Comment by smcv** [comment]
I'm not a debuerreotype maintainer, but conceptually this looks good to me.

**Comment by tianon** [comment]
:heart_eyes: I didn't expect you to review the implementation too, but I really appreciate that you did!

**Comment by tianon** [comment]
Here's a sample rootfs listing for unstable generated on today's timestamp (just to show it's working correctly, since the CI already verified that old timestamps are still correct :joy:):

```console
+ ls -lAFh /tmp/rootfs
total 4.0K
lrwxrwxrwx  1 root root    7 Aug 19 17:30 bin -> usr/bin/
drwxr-xr-x  2 root root   40 Jan 19  2022 boot/
-rw-rw-r--  1 root root   11 Aug 19 17:30 debuerreotype-epoch
drwxr-xr-x  4 root root  320 Aug 19 17:30 dev/
drwxr-xr-x 30 root root 1.4K Aug 19 17:30 etc/
drwxr-xr-x  2 root root   40 Jan 19  2022 home/
lrwxrwxrwx  1 root root    7 Aug 19 17:30 lib -> usr/lib/
lrwxrwxrwx  1 root root    9 Aug 19 17:30 lib32 -> usr/lib32/
lrwxrwxrwx  1 root root    9 Aug 19 17:30 lib64 -> usr/lib64/
lrwxrwxrwx  1 root root   10 Aug 19 17:30 libx32 -> usr/libx32/
drwxr-xr-x  2 root root   40 Aug 19 17:30 media/
drwxr-xr-x  2 root root   40 Aug 19 17:30 mnt/
drwxr-xr-x  2 root root   40 Aug 19 17:30 opt/
drwxr-xr-x  2 root root   40 Jan 19  2022 proc/
drwx------  2 root root   80 Aug 19 17:30 root/
drwxr-xr-x  4 root root  100 Aug 19 17:30 run/
lrwxrwxrwx  1 root root    8 Aug 19 17:30 sbin -> usr/sbin/
drwxr-xr-x  2 root root   40 Aug 19 17:30 srv/
drwxr-xr-x  2 root root   40 Jan 19  2022 sys/
drwxrwxrwt  2 root root   40 Aug 19 17:30 tmp/
drwxr-xr-x 14 root root  280 Aug 19 17:30 usr/
drwxr-xr-x 11 root root  260 Aug 19 17:30 var/
```

**Comment by tianon** [comment]
Just realized my methodology for that last post was wrong, but the actual code is still correct -- here's a more correct example demonstration:

```console
root@debuerreotype:/tmp/out/20220819/amd64# tar -tvf unstable/rootfs.tar.xz bin sbin lib
lrwxrwxrwx 0/0               0 2022-08-19 00:00 bin -> usr/bin
lrwxrwxrwx 0/0               0 2022-08-19 00:00 lib -> usr/lib
lrwxrwxrwx 0/0               0 2022-08-19 00:00 sbin -> usr/sbin

root@debuerreotype:/tmp/out/20220819/amd64# tar -tvf bookworm/rootfs.tar.xz bin sbin lib | wc -l
324
```

(A listing of `unstable` generated for today and `bookworm` for the same exact timestamp - the latter piped through `wc -l` because the list of files in each directory is not useful information.)

**Comment by tianon** [comment]
We had a few wrinkles around `usr-is-merged` that were fixed via #141, but the quirk fixed upstream in https://salsa.debian.org/installer-team/debootstrap/-/merge_requests/76 is much harder to fix without that updated `debootstrap` because `--exclude=usrmerge` doesn't successfully exclude it from the dependency set. :disappointed:

**Comment by tianon** [comment]
Ooof, even backporting https://salsa.debian.org/installer-team/debootstrap/-/merge_requests/76#note_340019 isn't enough to avoid `perl` and friends :weary:

**Pull request merged**
