### PR TITLE
Update to deb822-sources for bookworm (previously sid-only)

### PR DESCRIPTION
**Pull request by tianon**
This is the inevitable follow-up to https://github.com/debuerreotype/debuerreotype/pull/128

@julian-klode I'd love to hear your thoughts on whether you think we're ready to go to this next stage? :bow:
(I haven't heard of much bad breakage, but I imagine you're closer to where those might occur than I am :sweat_smile:)

### CODE REVIEW

**Comment by tianon** [comment]
<details>
<summary>`diffoscope` output for affected CI job:</summary>

```diff
@@ -102,16 +102,16 @@
 -rw-r--r--   0        0        0      754 2022-06-30 00:00:00.000000 etc/apt/apt.conf.d/docker-autoremove-suggests
 -rw-r--r--   0        0        0     1175 2022-06-30 00:00:00.000000 etc/apt/apt.conf.d/docker-clean
 -rw-r--r--   0        0        0      481 2022-06-30 00:00:00.000000 etc/apt/apt.conf.d/docker-gzip-indexes
 -rw-r--r--   0        0        0      269 2022-06-30 00:00:00.000000 etc/apt/apt.conf.d/docker-no-languages
 drwxr-xr-x   0        0        0        0 2022-05-17 16:50:45.000000 etc/apt/auth.conf.d/
 drwxr-xr-x   0        0        0        0 2022-05-17 16:50:45.000000 etc/apt/keyrings/
 drwxr-xr-x   0        0        0        0 2022-05-17 16:50:45.000000 etc/apt/preferences.d/
--rw-r--r--   0        0        0      430 2022-06-30 00:00:00.000000 etc/apt/sources.list
 drwxr-xr-x   0        0        0        0 2022-06-30 00:00:00.000000 etc/apt/sources.list.d/
+-rw-r--r--   0        0        0      443 2022-06-30 00:00:00.000000 etc/apt/sources.list.d/debian.sources
 drwxr-xr-x   0        0        0        0 2022-06-30 00:00:00.000000 etc/apt/trusted.gpg.d/
 -rw-r--r--   0        0        0     8700 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-bullseye-automatic.gpg
 -rw-r--r--   0        0        0     8709 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg
 -rw-r--r--   0        0        0     2453 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-bullseye-stable.gpg
 -rw-r--r--   0        0        0     8132 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-buster-automatic.gpg
 -rw-r--r--   0        0        0     8141 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-buster-security-automatic.gpg
 -rw-r--r--   0        0        0     2332 2021-02-25 17:38:08.000000 etc/apt/trusted.gpg.d/debian-archive-buster-stable.gpg
```

</details>

(as expected :+1:)

**Comment by tianon** [comment]
I've updated to combine "deb822" and "usr-is-merged" tests since their timestamps are so close together. :sweat_smile:

**Comment by julian-klode** [comment]
Presumably we should have the new apt.sources module and deprecation of aptsources done first before switching this, but not sure.

This moved from 22.10 to 23.04.

**Comment by tianon** [comment]
Ah yeah, totally makes sense!  Thanks for the update/consideration :heart:

**Comment by tianon** [comment]
`python-apt` 2.5.1 includes this:

```
   * aptsources: Initial deb822 reading, use SourcesList(..., deb822=True) to opt in.
     The .distro matcher code has not been fully ported yet, and you will
     experience issues trying to match distro entries to a deb822 source entry
     with multiple values in the Types, URIs, Suites field, but this should
     work for most use cases.
```

I think this was the last real blocker to moving forward with bookworm, so once this hits testing we're probably solid. :eyes:

**Comment by tianon** [comment]
https://tracker.debian.org/news/1413531/python-apt-252-migrated-to-testing/ :eyes:

**Comment by tianon** [comment]
https://lists.debian.org/debian-devel-announce/2023/02/msg00000.html :eyes:

**Pull request merged**
