### PR TITLE
Support building EOL-ed Ubuntu suite

### PR DESCRIPTION
**Pull request by vicamo**
This pull request tries to sync necessary features from `example/debian.sh` to support building EOL-ed Ubuntu suites.

### CODE REVIEW

**Comment by vicamo** [comment]
Use http instead of https.

**Comment by vicamo** [comment]
Install gpgv so that we support most series/arch since [Ubuntu 7.04 (Feisty Fawn)](http://old-releases.ubuntu.com/releases/feisty/).

**Comment by vicamo** [comment]
Use `--no-check-gpg` for those don't have gpgv.

**Comment by vicamo** [comment]
Fix Dapper and Breezy builds.

**Comment by vicamo** [comment]
Still have one last problem for Edgy [builds](https://github.com/vicamo/docker-brew-ubuntu-debootstrap/actions/runs/9006670030/job/24759022764):
```
I: Retrieving x11-common 1:7.1.1ubuntu6
I: Validating x11-common 1:7.1.1ubuntu6
I: Retrieving xkb-data 0.8-7ubuntu2
I: Validating xkb-data 0.8-7ubuntu2
...
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting base-files...
...
I: Extracting x11-common...
...
I: Installing core packages...
I: Unpacking required packages...
...
I: Unpacking x11-common...
...
I: Configuring required packages...
...
I: Configuring x11-common...
...
W: Failure while configuring required packages.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
...
W: Failure while configuring base packages.  This will be attempted 5 times.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
W: Failure while configuring base packages.  This will be attempted 5 times.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
W: Failure while configuring base packages.  This will be attempted 5 times.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
W: Failure while configuring base packages.  This will be attempted 5 times.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
W: Failure while configuring base packages.  This will be attempted 5 times.
W: See /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs/debootstrap/debootstrap.log for details (possibly the package x11-common is at fault)
I: Base system installed successfully.
...
+ debuerreotype-apt-get /tmp/debuerreotype.edgy.x6gAPstBVm/rootfs dist-upgrade -yq
Reading package lists...
Building dependency tree...
You might want to run `apt-get -f install' to correct these.
The following packages have unmet dependencies:
  console-setup: Depends: xkb-data (>= 0.8-7ubuntu2) but it is not installed
E: Unmet dependencies. Try using -f.
+ rm -rf /tmp/debuerreotype.edgy.x6gAPstBVm
```
Cannot reproduce locally, and *xkb-data* has been retrieved, but never unpacked, configured before

**Comment by tianon** [comment]
Doh, sorry, I should've gotten to this sooner :sob:

Since these are all combined now, I'll share my thoughts in aggregate:

---

As initial context, I'll start with the explanation that `examples/ubuntu.sh` is _not_ something I actually actively test or use.  It exists primarily as an example (heh) of how to use these scripts for non-Debian builds, and is not intended for serious usage as-is.  All my efforts maintaining it are best-effort to ensure it's an example with _rough_ parity to Debian, but is intentionally not perfect (partly because Canonical does not use it to build their images, to my knowledge, and partly because they do such a reasonable job maintaining their images that I don't feel the need to maintain my own for my own uses).

---

> Support building EOL-ed Ubuntu suite

Maybe with the above context it will not come as a surprise that this isn't actually something I'm very keen on supporting, sorry! :see_no_evil:

I think it's interesting and useful work, but also work that Canonical ought to be doing, IMO.

---

> Skip installing iputils-ping if unavailable

Given that the intent of https://github.com/debuerreotype/debuerreotype/blob/c5abe5d7e2c6db0a153e6068ce6a8f2ba2c29415/examples/debian.sh#L276-L278 was that we _stop_ installing these extra packages, I think I'd prefer to just axe this section of `ubuntu.sh` entirely instead (backwards compatibility doesn't matter to me much there like it does in `examples/debian.sh` which is actually load-bearing).

---

> Update checksum

This one is the most conflicting for me.  On the one hand, I'd love to have the CI passing again, but on the other, I've been using the failing CI as a needle in my side to keep reminding me that I really need to revamp the way this project uses CI such that those canonical (heh) artifacts are stored somewhere _other_ than in a directory on my personal machine so that they can more easily be compared when they need to or happen to change. :sob:

**Comment by vicamo** [comment]
> Doh, sorry, I should've gotten to this sooner 😭
> 
> Since these are all combined now, I'll share my thoughts in aggregate:
> 
> As initial context, I'll start with the explanation that `examples/ubuntu.sh` is _not_ something I actually actively test or use. It exists primarily as an example (heh) of how to use these scripts for non-Debian builds, and is not intended for serious usage as-is. All my efforts maintaining it are best-effort to ensure it's an example with _rough_ parity to Debian, but is intentionally not perfect (partly because Canonical does not use it to build their images, to my knowledge, and partly because they do such a reasonable job maintaining their images that I don't feel the need to maintain my own for my own uses).

Should not speak for Canonical, but I think we both agree Canonical is unlikely going to provide OCI/cloud images of EOL-ed releases as they're, by definition, EOL-ed. And, whether or not Canonical/Docker is taking advantage of these projects is not my concern at all. I feel like to fill the missing parts of Debian/Ubuntu docker images, so I find some time to complete them, send out the pull requests in case you may need them. Whether or not to accept them is up to your own decision based on your own interest. Git allows us to fork, and every forked repository has their own main trunk.

> > Support building EOL-ed Ubuntu suite
> 
> Maybe with the above context it will not come as a surprise that this isn't actually something I'm very keen on supporting, sorry! 🙈

No problem.

> I think it's interesting and useful work, but also work that Canonical ought to be doing, IMO.

I believe Canonical is doing their own job in a way that fits them best. Debootstrapping may not provide some key feature (snap?) such that Canonical has to switch to a more appropriate way. I might have to do the same, just like I switched from simple debootstrap to this project.

> > Skip installing iputils-ping if unavailable
> 
> Given that the intent of
> 
https://github.com/debuerreotype/debuerreotype/blob/c5abe5d7e2c6db0a153e6068ce6a8f2ba2c29415/examples/debian.sh#L276-L278
> 
> was that we _stop_ installing these extra packages, I think I'd prefer to just axe this section of `ubuntu.sh` entirely instead (backwards compatibility doesn't matter to me much there like it does in `examples/debian.sh` which is actually load-bearing).

ACK.

> > Update checksum
> 
> This one is the most conflicting for me. On the one hand, I'd love to have the CI passing again, but on the other, I've been using the failing CI as a needle in my side to keep reminding me that I really need to revamp the way this project uses CI such that those canonical (heh) artifacts are stored somewhere _other_ than in a directory on my personal machine so that they can more easily be compared when they need to or happen to change. 😭

I couldn't come up with a good solution at this moment since there is no such historical artifact ready for comparison.

I'm to postpone debugging Edgy for now, so I will close this as there is not strong need to support EOL-ed Ubuntu releases. Feel free to cherry-pick whatever you consider helpful.

**Pull request closed without merging**
